repo-name = bit-os
masters = gentoo
auto-sync = false
thin-manifests = true
# Assinatura Digital de Manifestos
# Define se o Portage deve exigir que os ficheiros Manifest estejam assinados 
# com uma chave GPG. Durante o desenvolvimento, mantém em 'false' para evitar 
# teres de assinar digitalmente cada ebuild que alteras.
sign-manifests = false
cache-formats = md5-cache
manifest-hashes = BLAKE2B SHA512
eapis-deprecated = 0 1 2 3 4 5 6
eapis-banned = 0 1 2 3 4 5 6